name: Deploy to Staging

on:
  push:
    branches: [ develop ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}

    - name: Deploy to staging
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.STAGING_PORT || 22 }}" \
        --exclude='.git' --exclude='.github' --exclude='node_modules' \
        ./ ${{ secrets.STAGING_USERNAME }}@${{ secrets.STAGING_HOST }}:~/staging/