name: Deploy to CPanel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js (if needed)
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup SSH with passphrase
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.CPANEL_SSH_KEY }}
        ssh-passphrase: ${{ secrets.CPANEL_SSH_PASSPHRASE }}

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.CPANEL_PORT || 22 }} \
        ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} "echo SSH connection successful"

    # ... rest of your workflow remains the same